version: 2.1


jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: cimg/node:20.5.1
    steps:
      - checkout

      - restore_cache: #Para restaurar las dependencias
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run: 
          name: Install dependencies #Es buena practica agregar el nombre del run
          command: npm install
      
      - save_cache: #Guarda las dependencias para que el siguiente deploy sea mas rapido la instalación
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run Lint
          command: npm run lint:report
      - run:
          name: Run tests
          command: npm run test:coverage
      - store_test_results: #Para subir los resultados en formato xml
          path: test-results.xml

workflows:
  test-wf:
    jobs:
      - test


