version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0  #Orb para el uso de sonarclouden circleci

jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: cimg/node:20.5.1
    steps:
      - checkout

      - restore_cache: #Para restaurar las dependencias
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run: 
          name: Install dependencies #Es buena practica agregar el nombre del run
          command: npm install
      
      - save_cache: #Guarda las dependencias para que el siguiente deploy sea mas rapido la instalación
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run Lint
          command: npm run lint:report
      - run:
          name: Run tests
          command: npm run test:coverage
      - store_test_results: #Para subir los resultados en formato xml
          path: test-results.xml
      - sonarcloud/scan

workflows:
  test-wf:
    jobs:
      - test
          context: sonarCloud #se llama el contexto creado en los settings de circleci

#Los contextos se usan para guardar secretos en circleci para guardas tokens
#El contexto se agrega desde los settings de la organizacon agregando como variable de ambiente
#Los contextos se añaden a nivel de workflow
#Se debe agregar un archivo soner-project.properties para configurar los test coverage en circleci